### PR TITLE
Parameterize rmd

### PR DESCRIPTION
**Pull request by SpaceGold**
@naupaka @melt6457 @mhaliz, everything works with my parameterizing, except that it doesn't save the filename properly when I don't put quotes around the state:

doesn't work:
`bash run_analyze_covid_pipeline.sh Oregon data/raw_data/applemobilitytrends-2020-10-10.
csvDD`

works:
`bash run_analyze_covid_pipeline.sh "Oregon" data/raw_data/applemobilitytrends-2020-10-10.
csvDD`

### CODE REVIEW

**Comment by naupaka** [comment]
hi @SpaceGold -- I am assigning reviews evenly across the TAs and myself to spread out the effort. Could you add Kory and Michali to this repo as collaborators, so that I can request their review?

**Review by melt6457 — CHANGES_REQUESTED** [review]
Hi @SpaceGold The parameterization bit of this assignment looks great! Although you had a number of lintr errors which need to be resolved. Please see #5. Once those are resolved, I'll take a look again. Nice work!!

**Comment by naupaka** [comment]
In the future, please don't merge until the PR is approved. It's a hassle to undo merges if there are still things that need to be fixed.

**Comment by SpaceGold** [comment]
Hi Dr. Z, Michali, and Kory, I was definitely one of the students who merged before getting the pull request approved. I did address the issues to the best of my knowledge. Thanks!

**Comment by SpaceGold** [comment]
Hi @naupaka @mhaliz @melt6457, I was definitely one of the students who merged before getting the pull request approved. I did address the issues to the best of my knowledge. Thanks!

**Comment by melt6457** [comment]
@SpaceGold Hey Adam, sorry I lost track of this, but the lintr fixes look great. Nice work!

**Pull request merged**
